version: "3.2"
services:
  mysql:
    image: mysql:5.5.60
    container_name: woutrunforlife-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=woutrunforlive
    networks:
      - backend
    ports:
      - "3306:3306"

  website:
    container_name: woutrunforlife-php
    build: .
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - mysql

networks:
  backend:
